name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy repository to arsen_test folder
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: 159.223.16.58
          username: arsen2  # Замініть, якщо потрібно інше ім'я користувача
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            # Видаляємо каталог test_halunka (якщо існує) і клонюємо репозиторій у нього
            rm -rf /home/arsen2/arsen_test
            git clone https://github.com/MobileGame20/GitHub1.git /home/arsen2/arsen_test
